[project]
name = "vni-total"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "mysql-connector-python>=9.3.0",
    "pandas>=2.3.0",
    "psycopg[binary,pool]>=3.2.9",
    "sqlalchemy>=2.0.41"
]
